# Code generated by https://codeberg.org/emicklei/schema2py from apis/citytaxi/v1/taxi_plan.schema.json. DO NOT EDIT.

# The future import postpones evaluation of annotations, which avoids runtime type-evaluation issues on older interpreters used in tooling/CI paths.
from __future__ import annotations

from datetime import datetime
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field, field_validator


Timestampz = Annotated[
    str, Field(description="Timestamp with time zone in RFC 3339 date-time format.")
]


class Address(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)
    street: str
    house_number: str
    city: str
    postal_code: str
    country_code: str = Field(
        ..., pattern=r"^[A-Z]{2}$", description="ISO 3166-1 alpha-2 country code."
    )


class TaxiPlan(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)
    id: str
    parent_id: str | None = None
    license_plate: str
    pickup_address: Address
    dropoff_address: Address
    estimated_pickup: Timestampz
    estimated_dropoff: Timestampz

    @field_validator("estimated_pickup", "estimated_dropoff")
    @classmethod
    def _validate_datetime(cls, v):
        if isinstance(v, datetime):
            return v
        if not isinstance(v, str):
            raise TypeError("expected str or datetime for date-time field")
        try:
            datetime.fromisoformat(v.replace("Z", "+00:00"))
        except ValueError as exc:
            raise ValueError(f"invalid RFC 3339 date-time: {v!r}") from exc
        return v
