# Code generated by https://codeberg.org/emicklei/schema2py from apis/airliner/v1/flight_plan.schema.json. DO NOT EDIT.

# The future import postpones evaluation of annotations, which avoids runtime type-evaluation issues on older interpreters used in tooling/CI paths.
from __future__ import annotations

from datetime import datetime
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field, field_validator


ICAOCode = Annotated[
    str,
    Field(
        pattern=r"^[A-Za-z0-9]{4}$",
        description="ICAO code represented as exactly 4 alphanumeric characters.",
    ),
]

Timestampz = Annotated[
    str, Field(description="Timestamp with time zone in RFC 3339 date-time format.")
]


class FlightPlan(BaseModel):
    """Details of a plan to fly from departure airport to destination airport"""

    model_config = ConfigDict(extra="forbid", strict=True)
    id: str
    parent_id: str | None = None
    aircraft_id: str
    creation_date: Timestampz
    departure: ICAOCode
    destination: ICAOCode = Field(..., description="Airport name of flight destination")
    estimated_takeoff: Timestampz
    estimated_landing: Timestampz

    @field_validator("creation_date", "estimated_takeoff", "estimated_landing")
    @classmethod
    def _validate_datetime(cls, v):
        if isinstance(v, datetime):
            return v
        if not isinstance(v, str):
            raise TypeError("expected str or datetime for date-time field")
        try:
            datetime.fromisoformat(v.replace("Z", "+00:00"))
        except ValueError as exc:
            raise ValueError(f"invalid RFC 3339 date-time: {v!r}") from exc
        return v
