python_requirement(
    name="pydantic",
    requirements=["pydantic>=2.0"],
)

python_sources(
    name="airliner",
    sources=["airliner/**/*.py"],
    dependencies=[":pydantic"],
)

python_sources(
    name="bikerental",
    sources=["bikerental/**/*.py"],
    dependencies=[":pydantic"],
)

python_sources(
    name="citytaxi",
    sources=["citytaxi/**/*.py"],
    dependencies=[":pydantic"],
)

python_sources(
    name="travelagent",
    sources=["travelagent/**/*.py"],
    dependencies=[":pydantic"],
)
