python_tests(
    name="tests",
    dependencies=[
        "//apps/travelagent/src:lib",
        "//pkgs/generated:travelagent",
        ":fixtures",
    ],
)

files(
    name="fixtures",
    sources=["fixtures/*.json"],
)
