# Code generated by codeberg.org/emicklei/schema2py from apis/travelagent/v1/journey.schema.json. DO NOT EDIT.

from __future__ import annotations

from datetime import datetime
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field, field_validator


Timestampz = Annotated[str, Field(description="Timestamp with time zone in RFC 3339 date-time format.")]


class Route(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)
    schema_version: str = Field(..., pattern=r"^[^/]+/v[0-9]+(?:[.][0-9]+)*$")
    properties: RouteProperties


class RouteProperties(BaseModel):
    model_config = ConfigDict(extra="allow", strict=True)
    pass


class Journey(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)
    id: str
    creation_date: Timestampz
    schema_version: str | None = None
    routes: list[Route]

    @field_validator("creation_date")
    @classmethod
    def _validate_datetime(cls, v):
        if isinstance(v, datetime):
            return v
        if not isinstance(v, str):
            raise TypeError("expected str or datetime for date-time field")
        try:
            datetime.fromisoformat(v.replace("Z", "+00:00"))
        except ValueError as exc:
            raise ValueError(f"invalid RFC 3339 date-time: {v!r}") from exc
        return v


